tamrin4/djangotamrin4/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import CreateUser, Search, NewSearch, EditNumber
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create/', CreateUser.as_view(), name='create'),
    path('search/', Search.as_view(), name='search'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('newsearch/', NewSearch.as_view(), name='new search'),
    path('editnumber/<int:pk>', EditNumber.as_view(), name='edit'),
]

tamrin4/accounts/models.py
from django.db import models

# Create your models here.

tamrin4/user/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.

phone_regex = RegexValidator(regex='^09[0-9]{9}$', message='phone number invalid')


class MyUser(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(validators=[phone_regex], max_length=11)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['phone_number', 'user'], name='unique number')
        ]

tamrin4/users/models.py
from django.db import models

# Create your models here.

tamrin4/user/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . import models


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(UserForm, self).__init__(*args, **kwargs)

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if models.MyUser.objects.filter(user=self.user, phone_number=phone_number).exists():
            raise ValidationError('omg')
        return phone_number

    class Meta:
        model = models.MyUser
        fields = [
            'first_name',
            'last_name',
            'phone_number',
        ]

tamrin4/accounts/views.py
from django.shortcuts import render

# Create your views here.

tamrin4/user/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import model_to_dict
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from user import forms, models
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
from user.forms import UserForm


@method_decorator(csrf_exempt, name='dispatch')
class CreateUser(LoginRequiredMixin, CreateView):
    model = models.MyUser
    form_class = UserForm

    def get_form_kwargs(self):
        kw = super(CreateUser, self).get_form_kwargs()
        kw.update({'user': self.request.user})
        return kw

    def form_invalid(self, form):
        return JsonResponse({'status': "error"})

    def form_valid(self, form):
        form.instance.user = self.request.user
        f = super().form_valid(form)
        return JsonResponse({'status': "ok"})


# @csrf_exempt
# @login_required
# def search(request):
#     if request.method == 'POST':
#         searched = request.POST.get('searched', None)
#         mode = request.POST.get('mode', None)
#         if mode == '1':
#             obj = models.MyUser.objects.filter(phone_number__contains=searched, user=request.user)
#         elif mode == '2':
#             obj = models.MyUser.objects.filter(phone_number=searched, user=request.user)
#         elif mode == '3':
#             obj = models.MyUser.objects.filter(phone_number__startswith=searched, user=request.user)
#         elif mode == '4':
#             obj = models.MyUser.objects.filter(phone_number__endswith=searched, user=request.user)
#         else:
#             return JsonResponse({'result': "error"})
#         if obj:
#             return JsonResponse({
#                 'results': list(obj.values())
#             })
#         else:
#             return JsonResponse({'result': "phone number not found !"})
#     else:
#         return render(request, 'search.html', {})


@method_decorator(csrf_exempt, name='dispatch')
class Search(LoginRequiredMixin, ListView):
    model = models.MyUser
    template_name = 'search.html'

    def get_queryset(self):
        queryset = self.model.objects.filter(user=self.request.user)
        return queryset

    def post(self, request, *args, **kwargs):
        searched = request.POST.get('searched', None)
        mode = request.POST.get('mode', None)
        if mode == '1':
            obj = models.MyUser.objects.filter(phone_number__contains=searched, user=request.user)
        elif mode == '2':
            obj = models.MyUser.objects.filter(phone_number=searched, user=request.user)
        elif mode == '3':
            obj = models.MyUser.objects.filter(phone_number__startswith=searched, user=request.user)
        elif mode == '4':
            obj = models.MyUser.objects.filter(phone_number__endswith=searched, user=request.user)
        else:
            return JsonResponse({'result': "error"})
        if obj:
            return JsonResponse({
                'results': list(obj.values()),
                'count': obj.count(),
            })
        else:
            return JsonResponse({'result': "phone number not found !"})


@method_decorator(csrf_exempt, name='dispatch')
class NewSearch(LoginRequiredMixin, ListView):
    model = models.MyUser
    template_name = 'newsearch.html'
    paginate_by = 5

    def get_queryset(self):
        searched = self.request.GET.get('searched', None)
        mode = self.request.GET.get('mode', None)
        if mode == '1':
            obj = models.MyUser.objects.filter(phone_number__contains=searched, user=self.request.user)
        elif mode == '2':
            obj = models.MyUser.objects.filter(phone_number=searched, user=self.request.user)
        elif mode == '3':
            obj = models.MyUser.objects.filter(phone_number__startswith=searched, user=self.request.user)
        elif mode == '4':
            obj = models.MyUser.objects.filter(phone_number__endswith=searched, user=self.request.user)
        else:
            obj = models.MyUser.objects.filter(user=self.request.user)
        return obj


class EditNumber(LoginRequiredMixin, UpdateView):
    model = models.MyUser
    template_name = 'editnumber.html'
    fields = {
        'first_name',
        'last_name',
        'phone_number',
    }
    success_url = '/'

    def get_queryset(self):
        number = models.MyUser.objects.filter(pk=self.kwargs['pk'], user=self.request.user)
        if number:
            return number
        else:
            raise Http404("No MyModel matches the given query.")

tamrin4/users/views.py
from django.shortcuts import render

# Create your views here.

tamrin4/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

tamrin4/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

tamrin4/user/templates/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

</form>
<button class="btn btn-info">Create</button>

</body>
<script>
    $(document).ready(function () {
        $("button").click(function (event) {
            var first_name = $('#id_first_name').val();
            var last_name = $('#id_last_name').val();
            var phone_number = $('#id_phone_number').val();
            $.ajax({
                method: 'POST',
                url: "/create/",
                data: {
                    first_name: first_name,
                    last_name: last_name,
                    phone_number: phone_number,
                 },
                success: function (response) {
                    alert(response.status);
                },

            });
        });
    });
</script>
</html>

tamrin4/user/templates/editnumber.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-info" type="submit">Edit</button>
</form>


</body>
</html>

tamrin4/user/templates/newsearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<form action="" method="get">
    <div>
        <label for="searched"></label><input placeholder="Search" name="searched" required id="searched" maxlength="11">
        <div>
        <label for="mode"></label><select id="mode" name="mode">
            <option value="1">bakhshi az shomare</option>
            <option value="2">kole shomare</option>
            <option value="3">shoroe shomare</option>
            <option value="4">payane shomare</option>
        </select>
        </div>
    </div>
    <button class="btn btn-info" type="submit">Search</button>
</form>
<table id="div1">
<tr>
    <th>first name : </th>
    <th>last name : </th>
    <th>phone number : </th>
</tr>
{% for obj in page_obj %}
    <tr>
        <th>{{ obj.first_name }}</th>
        <th>{{ obj.last_name }}</th>
        <th>{{ obj.phone_number }}<a href="{% url 'edit' obj.pk %}" >✏</th>
    </tr>
{% endfor %}
</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</body>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</html>

tamrin4/user/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<form action="" method="post">
    <input  placeholder="Search" name="searched" required id="searched" maxlength="11">
</form>
<div>
    <select id="mode">
        <option value="1">bakhshi az shomare</option>
        <option value="2">kole shomare</option>
        <option value="3">shoroe shomare</option>
        <option value="4">payane shomare</option>
    </select>
</div>
<button class="btn btn-info">Search</button>


<table id="div1">

</table>

<div class="center" style="text-align: center">
    <h4 id="count"></h4>
</div>
<script>
    $(document).ready(function () {
        $("button").click(function (event) {
            $('#div1').html('');
            $('#count').html('');
            var num = $('#searched').val();
            var mode = $('#mode').val()
            if (/^[0-9]{1,11}$/.test(num)) {
                $.ajax({
                    method: 'POST',
                    url: "/search/",
                    data: {
                        searched: num,
                        mode: mode,
                    },
                    success: function (request) {
                        $('#div1').append('<tr>')
                        $('#div1').append('<th>first name</th>')
                        $('#div1').append('<th>last name</th>')
                        $('#div1').append('<th>phone number</th>')
                        $('#div1').append('</tr>')
                        $(request.results).each(function (index, obj) {

                            $('#div1').append('<tr>')
                            $('#div1').append('<td>' + obj.first_name + '</td>')
                            $('#div1').append('<td>' + obj.last_name + '</td>')
                            $('#div1').append('<td>' + obj.phone_number + '</td>')
                            $('#div1').append('</tr>')
                            $('#count').html('result : ' +request.count)

                        });
                        if (request.result) {
                            $('#div1').html(request.result)
                        }

                    }
                });
            } else {
                alert('enter number only.');
            }
        });
    });
</script>
</body>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</html>

tamrin4/user/templates/user/myuser_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

</form>
<button class="btn btn-info">Create</button>

</body>
<script>
    $(document).ready(function () {
        $("button").click(function (event) {
            var first_name = $('#id_first_name').val();
            var last_name = $('#id_last_name').val();
            var phone_number = $('#id_phone_number').val();
            var user = $('#id_user').val();
            $.ajax({
                method: 'POST',
                url: "/create/",
                data: {
                    first_name: first_name,
                    last_name: last_name,
                    phone_number: phone_number,
                    user: user,
                 },
                success: function (response) {
                    alert(response.status);
                },

            });
        });
    });
</script>
</html>